### ISSUE TITLE
Expected answer for manual input Add picture function

### ISSUE THREAD

**Issue by leekoko** [labring/FastGPT#358]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [x ] 我已确认我已升级到最新版本
- [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
既然预期答案不会被搜索，那是否可以添加图片；
添加图片功能可以使用户在文本信息之外，还能通过图片来传达更多的信息或情感。

**应用场景**
一图胜万言：有时候，文字难以表达所有的信息，特别是在设计、艺术或者数据分析等领域。
笔记附图：很多人在做笔记或者整理个人知识库的时候，喜欢加入图表、图片或者截图。
**相关示例**

应用场景 | 详细描述
-- | --
美工素材库 | 美工或设计师需要一个可以存储大量图片和设计稿的库。
教育培训 | 教师或培训师在课件中添加图片，以增加学生或听众的兴趣和理解度。
医疗诊断 | 医生需要查看患者的X光片、MRI等医学图像。
旅游攻略 | 旅行者通过图片来展示目的地的风光，以便给其他人提供更直观的参考。
菜谱分享 | 在菜谱中添加步骤图片或成品图片，使读者更容易理解和跟随。
数据分析报告 | 分析师在报告中添加图表或数据可视化图片，以更直观地展示数据分析结果。
新闻报道 | 记者通过图片来增加报道的可信度和吸引力。
社交媒体营销 | 营销人员使用吸引人的图片来提高广告或帖子的点击率。

![截屏2023-09-27 09 47 53](https://github.com/labring/FastGPT/assets/23375386/1f0ff363-3c71-4e52-bf64-a7c4180c1616)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there are currently no similar features
- [x ] I have confirmed that I have upgraded to the latest version
- [x ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Since the answer is not expected to be searched, is it possible to add a picture?
Adding the picture function allows users to convey more information or emotions through pictures in addition to text information.

**Application Scenario**
A picture is worth a thousand words: Sometimes, words cannot convey all the information, especially in fields such as design, art, or data analysis.
Notes with pictures: Many people like to add charts, pictures or screenshots when taking notes or organizing their personal knowledge base.
**Related Examples**


Application scenarios | Detailed description
-- | --
Art Material Library | Artists or designers need a library that can store a large number of pictures and design drafts.
Education and Training | Teachers or trainers add images to courseware to increase student or audience interest and understanding.
Medical Diagnosis | Doctors need to view medical images such as X-rays and MRIs of patients.
Travel Guide | Travelers use pictures to show the scenery of their destinations to provide a more intuitive reference for others.
Recipe Sharing | Add step pictures or finished product pictures to the recipe to make it easier for readers to understand and follow.
Data analysis report | Analysts add charts or data visualization pictures to the report to more intuitively display the data analysis results.
News Reports | Journalists use images to add credibility and appeal to their reports.
Social Media Marketing | Marketers use attractive images to increase click-through rates on ads or posts.

**Comment by c121914yu** [comment]
markdown可以插入图片

**Comment by qdu123** [comment]
> markdown可以插入图片

how to do it?

i can add image by markdown,but the result has no image

**Comment by qdu123** [comment]
> markdown可以插入图片

我在手工导入数据中标记结果插入markdown图片，不过搜索时候，结果里面不显示对应的图片

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> markdown can insert pictures

I marked the results in the manually imported data and inserted markdown images, but when searching, the corresponding images were not displayed in the results.

**Comment by qdu123** [comment]
you can use vditor to replace textarea,then handle the image paste or select event to upload to your server, return the url back to your editor
