### ISSUE TITLE
[Suggestion] It is recommended to add a similarity variable in the reference template and make different answers based on the similarity.

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#380]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**相关示例**
![image](https://github.com/labring/FastGPT/assets/5433705/a2272c32-94c5-4d21-adc1-f5a776843060)
建议在引用模板中增加相似度的变量，这个就可以在回答时根据相似度不同做出不同的回答。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there are currently no similar features
- [ ] I have confirmed that I have upgraded to the latest version
- [ ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [ ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**

**Application Scenario**

**Related Examples**
![image](https://github.com/labring/FastGPT/assets/5433705/a2272c32-94c5-4d21-adc1-f5a776843060)
It is recommended to add a similarity variable to the reference template, so that different responses can be made based on the similarity when answering.

**Comment by c121914yu** [comment]
直接把低于阈值的去掉不就好了？

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/439 新增score变量，虽然大部分时候用不上，不过顺手加了。
