### ISSUE TITLE
Is it possible to directly return high-similarity content according to the similarity setting in advanced arrangement? When the similarity is too low, use AI dialogue

### ISSUE THREAD

**Issue by wm-network** [labring/FastGPT#390]
**功能描述**
例如设置相似度超过90，则以最高相似度直接回复，结束对话。
如果相似度未达到90，则使用ai对话，对多个结果进行改进。

**应用场景**
在某些接口形式调用场景，希望尽快的返回信息，由于经过ai模型加工后，返回时间至少要多加2-4秒的时间，因此希望常规高相似度问题，可以直接知识库QA内容返回

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Function description**
For example, if the similarity is set to exceed 90, the user will reply directly with the highest similarity and end the conversation.
If the similarity does not reach 90, use AI dialogue to improve multiple results.

**Application Scenario**
In some interface call scenarios, it is hoped that information will be returned as soon as possible. Since the return time will be at least 2-4 seconds longer after AI model processing, it is hoped that regular high-similarity questions can be directly returned to the knowledge base QA content.

**Comment by c121914yu** [comment]
高相似度可能有n个，不太好内置，建议可以用 HTTP 模块，自己定义排序和输出逻辑。

**Comment by wm-network** [comment]
了解了，可以用http模块自己控制的，是说可以不用ai对话，直接输出结果返回到对话框里的吗，抱歉还没能试验。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Understood, you can use the http module to control it yourself. Does that mean you can directly output the results back to the dialog box without AI dialogue? Sorry, I haven't been able to test it yet.

**Comment by c121914yu** [comment]
> 了解了，可以用http模块自己控制的，是说可以不用ai对话，直接输出结果返回到对话框里的吗，抱歉还没能试验。

是的

**Comment by wm-network** [comment]
![image](https://github.com/labring/FastGPT/assets/130726200/818b843d-250f-43ce-a612-6faadf786fda)
我尝试了下，在http模块得到的返回是类似的，这样无法直接回复到对话框里，这个要怎么操作呢。另外也希望像ai那样的stream形式返回

**Comment by c121914yu** [comment]
> ![image](https://user-images.githubusercontent.com/130726200/274491193-818b843d-250f-43ce-a612-6faadf786fda.png) 我尝试了下，在http模块得到的返回是类似的，这样无法直接回复到对话框里，这个要怎么操作呢。另外也希望像ai那样的stream形式返回

文档里有的例子就是从HTTP直接输出的

**Comment by wm-network** [comment]
找到了，原来是用指定回复，明白了，感谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Found it, it turns out I used the specified reply, I understand, thank you

**Comment by wm-network** [comment]
找到了，原来是用指定回复，明白了，感谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Found it, it turns out I used the specified reply, I understand, thank you
