### ISSUE TITLE
The content of the next step guide is abnormal.

### ISSUE THREAD

**Issue by leekoko** [labring/FastGPT#425]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
下一步指引的内容在切换不同聊天框的时候，显示的一直是最后一次聊天产生的下一步指引内容。

**复现步骤**
1. 打开 下一步指引
2. 打开不同的聊天界面，分别进行聊天
3. 查看不同聊天界面的下一步指引

**预期结果**
1. 下一步指引应该跟着聊天框，而不是全局只有一个

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there is currently no similar issue
- [x ] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x ] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
When switching between different chat boxes, the content of the next step guide will always be displayed in the last step of the chat.


**Steps to reproduce**
1. Open Next Steps
2. Open different chat interfaces and chat separately
3. View the next steps for different chat interfaces

**expected outcome**
1. The next step guide should follow the chat box, rather than having only one globally.

**Related screenshots**

**Comment by c121914yu** [comment]
fix： https://github.com/labring/FastGPT/pull/439
