### ISSUE TITLE
GPT4-V is not working

### ISSUE THREAD

**Issue by ws02589111** [labring/FastGPT#508]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

docker with v4.6.1 image
bump from v4.6

**问题描述**
When I set the model to GPT4-V, there is no response after clicking the "Select File" and "Voice Input" buttons.
**复现步骤**
Set model to GPT4-V and clicke the button
**预期结果**
Work well
**相关截图**

**Comment by c121914yu** [comment]
在window11 chrome中没有办法复现这个操作，可能需要你debug或者提供更多信息

**Comment by ws02589111** [comment]
Upgrading to the latest version 4.6.2 has resolved the issue.

**Comment by Starlento** [comment]
Hi all, a quick question. I am using v4.6.3 in docker.
And I am using a local openai_api Chatglm3 service, just want to try whether the image uploading function is working.
It give me. `connect ECONNREFUSED 127.0.0.1:3000`
And it shows the url for the image. 
```img-block
{"src":"http://localhost:3000/api/system/img/6570107ef967df6923b84156"}
```
The url is accessible using my host browser, it shows my uploaded image.
My question is: is this error exactly due to my LLM service do not support image input? Or I miss something under docker?
