### ISSUE TITLE
file imported into QA split. How to modify max_tokens?

### ISSUE THREAD

**Issue by lostmaniac** [labring/FastGPT#590]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
需要自定义QA问答对拆分时候的文本长度和max_tokens配置
**复现步骤**
后台拆分QA问答对时候，因为我是自建的chatglm-6b-32K，但是看到拆分问答对时候max_tokens=1024，有些文档干货很多，所以需要生成更多问答对，还有就是需要支持配置截取长度，我在config.json里没看到相关配置，max_tokens=1024可能会影响：比如我需要这个文档拆分出来更多的问答对，这样才能对文档吃的更透彻。
**预期结果**
自定义问答对拆分max_tokens，自定义配置截取长度
**相关截图**
暂无

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Need to customize the text length and max_tokens configuration when splitting QA question and answer pairs
**Steps to reproduce**
When splitting QA question and answer pairs in the background, because I built my own chatglm-6b-32K, but when I split the question and answer pairs, I saw max_tokens=1024. Some documents have a lot of useful information, so more question and answer pairs need to be generated, and support is needed. Configure the interception length. I did not see the relevant configuration in config.json. max_tokens=1024 may affect: For example, I need this document to be split into more question and answer pairs, so that I can understand the document more thoroughly.
**expected outcome**
Customize the question and answer pair split max_tokens, customize the interception length
**Related screenshots**
There is no
