### ISSUE TITLE
Knowledge base cannot be created after fresh installation of v4.6.6

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#715]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
部分系统不兼容，导致页面崩溃。如果可以，请联系作者，反馈下具体操作和页面。 大部分是 苹果 的 safari 浏览器导致，可以尝试更换 chrome 浏览器。或者是因为开了中文翻译导致，请检查并关闭中文翻译。
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Some systems are incompatible, causing the page to crash. If possible, please contact the author and provide feedback on the specific operations and pages. Most of them are caused by Apple's Safari browser. You can try to change the Chrome browser. Or it may be caused by turning on Chinese translation. Please check and turn off Chinese translation.
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by albert045** [comment]
I'm face the same issue can you share how to fix that？
