### ISSUE TITLE
Hope to add a pre-trained model library

### ISSUE THREAD

**Issue by dadastory** [labring/FastGPT#729]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x  ] 我已确认目前没有类似 features
- [x  ] 我已确认我已升级到最新版本
- [x  ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x  ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1.希望增加类似Next Chat那种面具管理的模型库，用来暂存一些预定义的模型参数提示词，以规范使用对应的模型
2.类似于知识库的那种，提前将模型的模板面具设置好存进去，然后高级编排或者简单编排时，可以直接选择对应的预定义模型
3.希望增加每次对话可以选择特定的几个预设置模型进行对话，而不是每次新增一个应用时单独手写这个模型的提示词
**应用场景**
1. 模型预设、简单对话
2. 高级编排预设模型
**相关示例**
预设模型参考项目https://github.com/PlexPt/awesome-chatgpt-prompts-zh
功能模型参考项目https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there are currently no similar features
- [x ] I have confirmed that I have upgraded to the latest version
- [x ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
1. I hope to add a model library similar to Next Chat’s mask management, which can be used to temporarily store some predefined model parameter prompt words to standardize the use of corresponding models.
2. Similar to a knowledge base, you can set the template mask of the model and save it in advance, and then you can directly select the corresponding predefined model during advanced or simple arrangement.
3. I hope to increase the ability to choose several preset models for each conversation instead of handwriting the prompt words for this model every time a new application is added.
**Application Scenario**
1. Model preset and simple dialogue
2. Advanced arrangement preset model
**Related Examples**
Default model reference project https://github.com/PlexPt/awesome-chatgpt-prompts-zh
Functional model reference project https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

**Comment by c121914yu** [comment]
用插件设置好不同子流程
