### ISSUE TITLE
Can the model configuration file be stored in the database as a configuration item?

### ISSUE THREAD

**Issue by dadastory** [labring/FastGPT#731]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1. 希望能将config的json中模型的配置改为在网页端的配置项进行配置，不然会导致每次添加模型时需要手动修改，并且重启影响业务
2. 希望可以通过openapi的接口直接读取接口对应可以使用的模型，我记得是有个标准可以获取模型的接口，希望可以通过这个模型列表接口可以直接加载这个模型数据进来，手动输入有时候多空格也可能引起失误
**应用场景**
1. 模型配置、价格配置、网页可以直接修改
2. 自动获取api所有可以使用的模型列表，并可以加载到配置参数中

**相关示例**
![image](https://github.com/labring/FastGPT/assets/84147842/67e6d8b5-d7df-4a0c-8c27-ca42cab6d3d9)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
1. It is hoped that the configuration of the model in the json of config can be changed to the configuration item on the web page. Otherwise, it will require manual modification every time a model is added, and restarting will affect the business.
2. I hope that I can directly read the available models corresponding to the interface through the openapi interface. I remember that there is a standard interface that can obtain the model. I hope that the model data can be directly loaded through this model list interface. Manual input is sometimes too much. Spaces may also cause errors
**Application Scenario**
1. Model configuration, price configuration, and web pages can be modified directly
2. Automatically obtain a list of all models that can be used by the API and load them into configuration parameters.

**Related Examples**
![image](https://github.com/labring/FastGPT/assets/84147842/67e6d8b5-d7df-4a0c-8c27-ca42cab6d3d9)

**Comment by c121914yu** [comment]
商业版支持
