### ISSUE TITLE
Ingress The controller cannot access this address

### ISSUE THREAD

**Issue by TheChalice** [labring/FastGPT#794]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
您好请问我在用k8s集群启动fastgtp时，发现服务启动在Local: http://dcbf1e94e359:3000
·Network: http://172.23.0.2:3000上，但是Ingress 控制器通常无法直接访问到这个特定的IP地址，因为它是容器内部的私有地址。
我应该怎么处理您这边有什么好的解决方案吗
**复现步骤**

**预期结果**
改变fastgtp Network，或者使Ingress访问到这个ip
**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Hello, when I use k8s cluster to start fastgtp, I found that the service is started in Local: http://dcbf1e94e359:3000
·Network: http://172.23.0.2:3000, but the Ingress controller usually cannot directly access this specific IP address because it is a private address inside the container.
What should I do? Do you have any good solutions?
**Steps to reproduce**

**expected outcome**
Change fastgtp Network, or enable Ingress to access this IP
**Related screenshots**

**Comment by c121914yu** [comment]
ingress不应该指向service么？应该起一个service指向容器，ingress指向service
