### ISSUE TITLE
When jumping to fastgpt through the nginx configuration link, there will be a problem that the page cannot be loaded.

### ISSUE THREAD

**Issue by linshao520** [labring/FastGPT#812]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [# ] 私有部署版本

**问题描述**
因为是内网部署的，内网只能通过特定域名和80访问。通过nginx配置跳转以后，一直卡在首页
**复现步骤**，
然后在内网负责跳转的nginx上做了如下配置
location /fastgpt/ {
        proxy_pass http://192.168.137.111:3000/ 
        }
配置好以后，访问如下地址 http://内网域名/fasgtgpt/，可以显示跳转到了fastgpt的页面，但是页面上的相关css，静态资源等都报404错误，导致页面一直卡在那。
经过与内网管理员沟通，放开所有接口限制以后，问题依然存在。
**预期结果**
能通过nginx的配置，通过特定域名和链接能正常访问fastgpt

**相关截图**
![16470ca3043046873766a0a6018c4b9](https://github.com/labring/FastGPT/assets/29830183/3850a5ac-2d7f-4c85-b4e9-308fe14a3694)
![bug](https://github.com/labring/FastGPT/assets/29830183/b39b7cee-ed8a-48fd-9077-3093a59b3c85)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [# ] Private deployment version

**Problem Description**
Because it is deployed on the intranet, the intranet can only be accessed through a specific domain name and 80. After jumping through nginx configuration, I am always stuck on the home page.
**Reproduction Steps**,
Then I made the following configuration on nginx, which is responsible for jumping on the intranet
location /fastgpt/ {
        proxy_pass http://192.168.137.111:3000/
        }
After the configuration is complete, visit the following address http://intranet domain name/fasgtgpt/, and you can see that you have jumped to the fastgpt page, but the relevant css, static resources, etc. on the page all report 404 errors, causing the page to stay stuck there.
After communicating with the intranet administrator and releasing all interface restrictions, the problem still exists.
**expected outcome**
Through nginx configuration, fastgpt can be accessed normally through specific domain names and links.

**Related screenshots**
![16470ca3043046873766a0a6018c4b9](https://github.com/labring/FastGPT/assets/29830183/3850a5ac-2d7f-4c85-b4e9-308fe14a3694)
![bug](https://github.com/labring/FastGPT/assets/29830183/b39b7cee-ed8a-48fd-9077-3093a59b3c85)

**Comment by linshao520** [comment]
经过测试，发现可能是因为fastgpt加载css或者js等静态资源使用的是相对地址造成的。通过nginx链接跳转到fastgpt后，由于_next/xxx/yyy等相关文件还是在http://内网链接/_next/...下，而不是在http://内网链接/fastgpt/_next/...，导致跳转过去后的资源地址都提示404或者500

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
After testing, it was found that it may be caused by fastgpt loading static resources such as css or js using relative addresses. After jumping to fastgpt through the nginx link, the related files such as _next/xxx/yyy are still under http://intranet link/_next/... instead of http://intranet link/fastgpt/_next /..., causing the resource address after the jump to prompt 404 or 500

**Comment by c121914yu** [comment]
可以自己重新编译打包。

**Comment by c121914yu** [comment]
> 可以自己重新编译打包。

具体规则可以参考 nextjs 官网

**Comment by fzcccc** [comment]
请问你解决了吗，我也遇到了这个问题
